services:
  gitea:
    image: gitea/gitea:1.22.0-rootless
    container_name: gitea
    environment:
      - USER=${USER}
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__DOMAIN=${DOMAIN}
      - GITEA__server__SSH_DOMAIN=${DOMAIN}
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__ROOT_URL=${ROOT_URL}
      - GITEA__server__SSH_PORT=${SSH_PORT}
      - GITEA__server__SSH_LISTEN_PORT=${SSH_LISTEN_PORT}
      - GITEA__server__BUILTIN_SSH_SERVER_USER=git
      - GITEA__server__SSH_CREATE_AUTHORIZED_KEYS_FILE=true
      - GITEA__server__LFS_START_SERVER=true
      - GITEA__server__SSH_EXPOSE_ANONYMOUS=true
      - GITEA__server__LANDING_PAGE=explore
      - GITEA__server__OFFLINE_MODE=true
      - GITEA__database__DB_TYPE=${DB_TYPE}
      - GITEA__database__HOST=${DB_HOST}
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASSWD}
      - GITEA__database__LOG_SQL=false
      - GITEA__database__SSL_MODE=false
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__security__PASSWORD_HASH_ALGO=bcrypt
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__REQUIRE_SIGNIN_VIEW=false
      - GITEA__service__REGISTER_EMAIL_CONFIRM=false
      - GITEA__service__ENABLE_NOTIFY_MAIL=false
      - GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION=false
      - GITEA__service__ENABLE_CAPTCHA=true
      - GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE=false
      - GITEA__service__DEFAULT_ALLOW_CREATE_ORGANIZATION=true
      - GITEA__service__DEFAULT_ENABLE_TIMETRACKING=true
      - GITEA__service__REQUIRE_CAPTCHA_FOR_LOGIN=true
      - GITEA__service__CAPTCHA_TYPE=image
      - GITEA__openid__ENABLE_OPENID_SIGNIN=false
      - GITEA__openid__ENABLE_OPENID_SIGNUP=false
      - GITEA__storage__STORAGE_TYPE=minio
      - GITEA__storage__MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - GITEA__storage__MINIO_BUCKET=${MINIO_BUCKET}
      - GITEA__storage__MINIO_ACCESS_KEY_ID=${MINIO_ACCESS_KEY_ID}
      - GITEA__storage__MINIO_SECRET_ACCESS_KEY=${MINIO_SECRET_ACCESS_KEY}
      - GITEA__repository.upload__FILE_MAX_SIZE=${UPLOAD_FILE_MAX_SIZE}
      - GITEA__i18n__LANGS=en-US,zh-CN
      - GITEA__i18n__NAMES=English,简体中文
      - GITEA__other__SHOW_FOOTER_VERSION=false
      - GITEA__other__SHOW_FOOTER_TEMPLATE_LOAD_TIME=false
      - GITEA__other__SHOW_FOOTER_POWERED_BY=false
      - GITEA__api__ENABLE_SWAGGER=false
      - GITEA__time__DEFAULT_UI_LOCATION=Asia/Shanghai
      - GITEA__ui__SHOW_USER_EMAIL=false
      - GITEA__cron.resync_all_sshkeys__ENABLED=true
      - GITEA__cron.resync_all_sshkeys__RUN_AT_START=true
      - GITEA__cron.update_checker__ENABLED=false
      - GITEA__repository.pull-request__DEFAULT_MERGE_STYLE=merge
      - GITEA__repository.signing__DEFAULT_TRUST_MODEL=committer
      - GITEA__mailer__ENABLED=false
    restart: unless-stopped
    user: 1000:1000
    networks:
      - gitea
      - mysql
      - minio
    volumes:
      - ./data/gitea:/var/lib/gitea
      - ./config/gitea:/etc/gitea
      - ./.runner_token:/.runner_token:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:3000" ]
      interval: 10s
      timeout: 1s
      retries: 1
    ports:
      - "${HTTP_PORT}:3000"
      - "${SSH_PORT}:2222"
    command: /bin/sh -c \
      "nohup /usr/local/bin/gitea web -c /etc/gitea/app.ini > ~/gitea.log 2>&1 & \
      while true; do if grep -q \"Starting new Web server\" ~/gitea.log; then echo $(/usr/local/bin/gitea --config /etc/gitea/app.ini actions generate-runner-token | tail -n 1) > ~/runner_registration_token; break; else sleep 1; fi done && \
      cat ~/runner_registration_token && \
      echo GITEA_RUNNER_REGISTRATION_TOKEN= > /.runner_token && \
      sed \"s/GITEA_RUNNER_REGISTRATION_TOKEN=.*/GITEA_RUNNER_REGISTRATION_TOKEN=$(cat ~/runner_registration_token)/\" /.runner_token > ~/.runner_token && \
      rm ~/runner_registration_token && \
      cat ~/.runner_token > /.runner_token && \
      rm ~/.runner_token && \
      tail -f ~/gitea.log"

  runner:
    image: gitea/act_runner:0.2.10
    container_name: runner
    environment:
      - CONFIG_FILE=/config.yaml
      - GITEA_INSTANCE_URL=http://gitea:3000/
    volumes:
      - ./config/runner/config.yaml:/config.yaml:ro
      - ./data/runner:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.runner_token:/.runner_token:ro
    networks:
      - gitea
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      gitea:
        condition: service_healthy
    entrypoint: /bin/sh -c "cat /.runner_token && export $(cat /.runner_token) && /sbin/tini -- /opt/act/run.sh"


networks:
  gitea:
    name: gitea
    external: false
  mysql:
    external: true
  minio:
    external: true